---

- name  : Create consul group
  group :
    name : "{{ consul_group }}"

- name : Create consul user
  user :
    name : "{{ consul_user }}"

- name      : Create directories for consul
  file      :
    path  : "{{item}}"
    state : directory
    owner : consul
    group : consul
    mode  : "0750"
  with_items :
    - "{{ consul_config_dir }}"
    - /opt/consul
    - /opt/consul/data
    - "{{ consul_tls_dir }}"
