---

- name: Consul base
  hosts: all
  become: true
  roles:
    - base
    - consul-common

- name: Consul internal networking encryption
  hosts: all
  become: true
  roles: 
    - consul-tls

- name: Consul health checks
  hosts: all
  become: true
  roles:
    - consul-health-checks