---

all:
  vars:
    ansible_host_key_checking: false
  children:
    consul_servers:
      vars:
        ansible_user      : playground
        ansible_ssh_pass  : # Add server password
        ansible_sudo_pass : # Add server password
      hosts:
        # Add target instance IP
    consul_clients:
      vars: 
        ansible_user: playground
        ansible_ssh_pass  : # Add server password
        ansible_sudo_pass : # Add server password
      hosts:
        # Add the host instance IP