---

- name     : Check for encryption key
  stat     :
    path : "{{ encryption_key_file }}"
  register : key_file_present 

- name    : Generate encryption key
  command :
    cmd       : consul keygen
    reggister : consul_encryption_key
  when    : not key_file_present.stat.exists 

- name : Store in local file
  copy :
    content : consul_encryprion_key.stdout
    dest    : "{{ encryption_key_file }}"
    mode    : 0600
  when : not key_file_present.stat.exists